export const testCart = [
    {
        product: {
            sku: 194,
            brand: 'vivienne westwood',
            productName: 'Corinne crystal-embellished hair clip',
            productId: '6703000C02R108IM',
            shippingFee: 15000,
            price: 349000,
            intl: true,
            searchInfo:
                'vivienne westwood 비비안웨스트우드 Corinne crystal-embellished hair clip 크리스탈 헤어 클립 6703000C02R108IM',
            color: '\bGOLD',
            category: '기타',
            categorySpec: '기타',
            imgType: 'webp',
            priceDescCursor: '034900000194',
            priceAscCursor: '65099999806',
            deploy: 1,
            korProductName: '크리스탈 헤어 클립',
            korBrand: '비비안웨스트우드',
            edges: {},
            size: ['ONE SIZE'],
        },
        size: 'ONE SIZE',
        quantity: 1,
        checked: true,
    },
    {
        product: {
            sku: 189,
            brand: 'adidas originals',
            productName: '3 stripe half zip crew sweater arctic night white',
            productId: 'IL2500',
            shippingFee: 15000,
            price: 83000,
            intl: true,
            searchInfo:
                'adidas originals 아디다스 오리지널스 3 stripe half zip crew sweater arctic night white 3 스트라이프 하프 집 크루 스웨터 아크틱 나이트 화이트 IL2500',
            color: 'ARCTIC NIGHT/WHITE',
            category: '의류',
            categorySpec: '자켓',
            imgType: 'webp',
            priceDescCursor: '008300000189',
            priceAscCursor: '91699999811',
            deploy: 1,
            korProductName: '3 스트라이프 하프 집 크루 스웨터 아크틱 나이트 화이트',
            korBrand: '아디다스 오리지널스',
            edges: {},
            size: ['M', 'S', 'XS'],
        },
        size: 'M',
        quantity: 1,
        checked: true,
    },
]
